Added service definition support.

diff --git a/shim b/shim
--- a/shim
+++ b/shim
@@ -20,6 +20,7 @@
 # SVCDEFNAME  the path name of the service definition
 # LIVESVC    the path name of the live service
 # LASTRESULT  the return code of the last command
+# STARTWAIT   the number of seconds to wait for successful start
 
 # In os-settings:
 # PATH     the file path to be searched by this script
@@ -35,6 +36,14 @@
 # Change DEBUG to 1 instead of 0 to display values at runtime.
 DEBUG=0
 [ $DEBUG -eq 1 ] && echo "DEBUG mode is on."
+
+# Define the result scratchpad
+LASTRESULT=0
+
+# Number of seconds to wait for supervisor to report back.
+# If set to zero, the start of the service is left to the
+# supervisor and is considered an "asynchronous" start
+STARTWAIT=7
 
 # Where do I live? (i.e. where is my init.d collection)
 MYHOME=$( dirname $0 )
@@ -61,8 +70,10 @@ SVCNAME=$MYNAME
 
 # detect if the settings were not changed.
 [ "$PATH" = "fail" ] && echo "Failed to load PATH setting." && exit 1
+[ "$SVCDEF" = "fail" ] && echo "Failed to load service directory definition setting." && exit 1
 [ "$SVCDIR" = "fail" ] && echo "Failed to load service directory location setting." && exit 1
 [ $DEBUG -eq 1 ] && echo "PATH: $PATH"
+[ $DEBUG -eq 1 ] && echo "SVCDEF: $SVCDEF"
 [ $DEBUG -eq 1 ] && echo "SVCDIR: $SVCDIR"
 
 # Where is the (live) supervision directory for the daemon?
@@ -93,24 +104,86 @@ SVCDEFNAME=$SVCDEF/$SVCNAME
 # any supervisor command is guaranteed to fail.
 if [ ! -d $LIVESVC ];
 then
-  echo "$MYNAME: no live definition exists at $LIVESVC"
+  echo "$MYNAME: WARNING: no live definition exists at $LIVESVC"
 fi
 
 
 # Process the request
 case "$1" in
   start)
-    # Ask the supervisor to start the daemon.
-    $SVCCTRL $CMDSTART $LIVESVC
-    LASTRESULT=$?
+    # A service definition needs to exist.
+    if [ ! -d $SVCDEF/$SVCNAME ];
+    then
+      echo "$MYNAME: cannot start service without a definition.  Aborting."
+      exit 1
+    else
+      [ $DEBUG -eq 1 ] && echo "Service definition found at $SVCDEF/$SVCNAME."
+    fi
+
+    # A live instance of the service definition needs to exist.
+    if [ ! -d $LIVESVC ];
+    then
+      echo "$MYNAME: cannot start service without a live instance.  Aborting."
+      exit 1
+    else
+      [ $DEBUG -eq 1 ] && echo "Service live instance found at $LIVESVC."
+    fi
+
+    # A service scan link of the live instance needs to exist.
+    if [ -L $SVCSCAN/$SVCNAME ];
+    then
+      [ $DEBUG -eq 1 ] && echo "$MYNAME: WARNING: service scan link already exists."
+    else
+      ln -s $LIVESVC $SVCSCAN/$SVCNAME
+      LASTRESULT=$?
+      [ $DEBUG -eq 1 ] && echo "$MYNAME: service scan link created."
+    fi
+
+    # After a successful link, start the daemon.
+    if [ $LASTRESULT -eq 0 ];
+    then
+      # wait for a confirmation that a supervisor is running for the service
+      # NOTE: runit provides feedback that requires we send output to /dev/null
+      $SVCSTATUS $SVCNAME >/dev/null
+      LASTRESULT=$?
+      until [ $STARTWAIT -eq 0 -o $LASTRESULT -eq 0 ];
+      do
+        sleep 1 # pause before checking again
+        $SVCSTATUS $SVCNAME >/dev/null
+        LASTRESULT=$?
+        STARTWAIT=`expr $STARTWAIT - 1`
+      done
+
+      #
+      if [ $LASTRESULT -eq 0 -a $STARTWAIT -gt 0 ];
+      then
+        $SVCCTRL $CMDSTART $SVCNAME
+        LASTRESULT=$?
+      else
+        # supervisor does not appear to be successful in launching.
+        echo "$MYNAME: ERROR: supervisor was not successfully launched."
+        exit 1
+      fi
+
+    fi
+
     exit $LASTRESULT
     ;;
+
   stop)
     # Ask the supervisor to stop the daemon.
-    $SVCCTRL $CMDSTOP $LIVESVC
+    $SVCCTRL $CMDSTOP $SVCNAME
     LASTRESULT=$?
+
+    # After a successful stop, remove the service link.
+    if [ $LASTRESULT -eq 0 ];
+    then
+      rm $SVCSCAN/$SVCNAME
+      LASTRESULT=$?
+    fi
     exit $LASTRESULT
     ;;
+
   restart)
     # Ask the supervisor to stop, then start the daemon.
     $SVCCTRL $CMDSTOP $LIVESVC && $SVCCTRL $CMDSTART $LIVESVC
